name: Upload coverage reports to Codecov
on: [push, pull_request]
jobs:
    codecov:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: |
                  cd backend/
                  yarn install

            - name: Run Hardhat tests
              run: |
                  cd backend/ 
                  yarn hardhat coverage

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              env:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  directory: backend/coverage
                  slug: manthis/alyra-certification/backend
                  flags: backend # Facultatif: Ajoute des flags pour différencier les rapports d'environnement
                  fail_ci_if_error: true # Facultatif: Le CI échouera si l'envoi échoue
                  verbose: true
