name: Upload coverage reports to Codecov
on: [push, pull_request]
jobs:
    codecov:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2

            - name: Move to backend dir
              run: cd backend/

            - name: Install dependencies
              run: yarn install

            - name: Run Hardhat tests
              run: yarn hardhat coverage

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              env:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: manthis/alyra-certification
